# Generated by Django 5.0.2 on 2024-03-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_short_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
